// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file offline_ticket.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file offline_ticket.proto.
 */
export const file_offline_ticket: GenFile = /*@__PURE__*/
  fileDesc("ChRvZmZsaW5lX3RpY2tldC5wcm90byJ3Cg5PZmZsaW5lX1RpY2tldBIYChBlbmNyeXB0ZWRfdGlja2V0GAEgASgMEhEKCXNpZ25hdHVyZRgCIAEoDBIMCgRrZGYxGAMgASgFEg0KBXNhbHQxGAQgASgMEgwKBGtkZjIYBSABKAUSDQoFc2FsdDIYBiABKAw");

/**
 * @generated from message Offline_Ticket
 */
export type Offline_Ticket = Message<"Offline_Ticket"> & {
  /**
   * @generated from field: optional bytes encrypted_ticket = 1;
   */
  encryptedTicket: Uint8Array;

  /**
   * @generated from field: optional bytes signature = 2;
   */
  signature: Uint8Array;

  /**
   * @generated from field: optional int32 kdf1 = 3;
   */
  kdf1: number;

  /**
   * @generated from field: optional bytes salt1 = 4;
   */
  salt1: Uint8Array;

  /**
   * @generated from field: optional int32 kdf2 = 5;
   */
  kdf2: number;

  /**
   * @generated from field: optional bytes salt2 = 6;
   */
  salt2: Uint8Array;
};

/**
 * Describes the message Offline_Ticket.
 * Use `create(Offline_TicketSchema)` to create a new message.
 */
export const Offline_TicketSchema: GenMessage<Offline_Ticket> = /*@__PURE__*/
  messageDesc(file_offline_ticket, 0);

