// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file steammessages_gamerecording_objects.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_enums } from "./enums_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file steammessages_gamerecording_objects.proto.
 */
export const file_steammessages_gamerecording_objects: GenFile = /*@__PURE__*/
  fileDesc("CilzdGVhbW1lc3NhZ2VzX2dhbWVyZWNvcmRpbmdfb2JqZWN0cy5wcm90byK8AgowQ0dhbWVSZWNvcmRpbmdfQXVkaW9TZXNzaW9uc0NoYW5nZWRfTm90aWZpY2F0aW9uEksKCHNlc3Npb25zGAEgAygLMjkuQ0dhbWVSZWNvcmRpbmdfQXVkaW9TZXNzaW9uc0NoYW5nZWRfTm90aWZpY2F0aW9uLlNlc3Npb24augEKB1Nlc3Npb24SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIRCglpc19zeXN0ZW0YAyABKAgSEAoIaXNfbXV0ZWQYBCABKAgSEQoJaXNfYWN0aXZlGAUgASgIEhMKC2lzX2NhcHR1cmVkGAYgASgIEhMKC3JlY2VudF9wZWFrGAcgASgCEg8KB2lzX2dhbWUYCCABKAgSEAoIaXNfc3RlYW0YCSABKAgSEAoIaXNfc2F2ZWQYCiABKAhCBUgBgAEA", [file_enums]);

/**
 * @generated from message CGameRecording_AudioSessionsChanged_Notification
 */
export type CGameRecording_AudioSessionsChanged_Notification = Message<"CGameRecording_AudioSessionsChanged_Notification"> & {
  /**
   * @generated from field: repeated CGameRecording_AudioSessionsChanged_Notification.Session sessions = 1;
   */
  sessions: CGameRecording_AudioSessionsChanged_Notification_Session[];
};

/**
 * Describes the message CGameRecording_AudioSessionsChanged_Notification.
 * Use `create(CGameRecording_AudioSessionsChanged_NotificationSchema)` to create a new message.
 */
export const CGameRecording_AudioSessionsChanged_NotificationSchema: GenMessage<CGameRecording_AudioSessionsChanged_Notification> = /*@__PURE__*/
  messageDesc(file_steammessages_gamerecording_objects, 0);

/**
 * @generated from message CGameRecording_AudioSessionsChanged_Notification.Session
 */
export type CGameRecording_AudioSessionsChanged_Notification_Session = Message<"CGameRecording_AudioSessionsChanged_Notification.Session"> & {
  /**
   * @generated from field: optional string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional bool is_system = 3;
   */
  isSystem: boolean;

  /**
   * @generated from field: optional bool is_muted = 4;
   */
  isMuted: boolean;

  /**
   * @generated from field: optional bool is_active = 5;
   */
  isActive: boolean;

  /**
   * @generated from field: optional bool is_captured = 6;
   */
  isCaptured: boolean;

  /**
   * @generated from field: optional float recent_peak = 7;
   */
  recentPeak: number;

  /**
   * @generated from field: optional bool is_game = 8;
   */
  isGame: boolean;

  /**
   * @generated from field: optional bool is_steam = 9;
   */
  isSteam: boolean;

  /**
   * @generated from field: optional bool is_saved = 10;
   */
  isSaved: boolean;
};

/**
 * Describes the message CGameRecording_AudioSessionsChanged_Notification.Session.
 * Use `create(CGameRecording_AudioSessionsChanged_Notification_SessionSchema)` to create a new message.
 */
export const CGameRecording_AudioSessionsChanged_Notification_SessionSchema: GenMessage<CGameRecording_AudioSessionsChanged_Notification_Session> = /*@__PURE__*/
  messageDesc(file_steammessages_gamerecording_objects, 0, 0);

