// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file steammessages_clientserver_ufs.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_steammessages_base } from "./steammessages_base_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file steammessages_clientserver_ufs.proto.
 */
export const file_steammessages_clientserver_ufs: GenFile = /*@__PURE__*/
  fileDesc("CiRzdGVhbW1lc3NhZ2VzX2NsaWVudHNlcnZlcl91ZnMucHJvdG8iRAoaQ01zZ0NsaWVudFVGU0dldFVHQ0RldGFpbHMSJgoIaGNvbnRlbnQYASABKAY6FDE4NDQ2NzQ0MDczNzA5NTUxNjE1IuUBCiJDTXNnQ2xpZW50VUZTR2V0VUdDRGV0YWlsc1Jlc3BvbnNlEhIKB2VyZXN1bHQYASABKAU6ATISCwoDdXJsGAIgASgJEg4KBmFwcF9pZBgDIAEoDRIQCghmaWxlbmFtZRgEIAEoCRIXCg9zdGVhbWlkX2NyZWF0b3IYBSABKAYSEQoJZmlsZV9zaXplGAYgASgNEhwKFGNvbXByZXNzZWRfZmlsZV9zaXplGAcgASgNEhcKD3JhbmdlY2hlY2tfaG9zdBgIIAEoCRIZChFmaWxlX2VuY29kZWRfc2hhMRgJIAEoCSJDCh5DTXNnQ2xpZW50VUZTR2V0U2luZ2xlRmlsZUluZm8SDgoGYXBwX2lkGAEgASgNEhEKCWZpbGVfbmFtZRgCIAEoCSK4AQomQ01zZ0NsaWVudFVGU0dldFNpbmdsZUZpbGVJbmZvUmVzcG9uc2USEgoHZXJlc3VsdBgBIAEoBToBMhIOCgZhcHBfaWQYAiABKA0SEQoJZmlsZV9uYW1lGAMgASgJEhAKCHNoYV9maWxlGAQgASgMEhIKCnRpbWVfc3RhbXAYBSABKAQSFQoNcmF3X2ZpbGVfc2l6ZRgGIAEoDRIaChJpc19leHBsaWNpdF9kZWxldGUYByABKAgiOwoWQ01zZ0NsaWVudFVGU1NoYXJlRmlsZRIOCgZhcHBfaWQYASABKA0SEQoJZmlsZV9uYW1lGAIgASgJIlwKHkNNc2dDbGllbnRVRlNTaGFyZUZpbGVSZXNwb25zZRISCgdlcmVzdWx0GAEgASgFOgEyEiYKCGhjb250ZW50GAIgASgGOhQxODQ0Njc0NDA3MzcwOTU1MTYxNUIFSAGAAQA", [file_steammessages_base]);

/**
 * @generated from message CMsgClientUFSGetUGCDetails
 */
export type CMsgClientUFSGetUGCDetails = Message<"CMsgClientUFSGetUGCDetails"> & {
  /**
   * @generated from field: optional fixed64 hcontent = 1 [default = 18446744073709551615];
   */
  hcontent: bigint;
};

/**
 * Describes the message CMsgClientUFSGetUGCDetails.
 * Use `create(CMsgClientUFSGetUGCDetailsSchema)` to create a new message.
 */
export const CMsgClientUFSGetUGCDetailsSchema: GenMessage<CMsgClientUFSGetUGCDetails> = /*@__PURE__*/
  messageDesc(file_steammessages_clientserver_ufs, 0);

/**
 * @generated from message CMsgClientUFSGetUGCDetailsResponse
 */
export type CMsgClientUFSGetUGCDetailsResponse = Message<"CMsgClientUFSGetUGCDetailsResponse"> & {
  /**
   * @generated from field: optional int32 eresult = 1 [default = 2];
   */
  eresult: number;

  /**
   * @generated from field: optional string url = 2;
   */
  url: string;

  /**
   * @generated from field: optional uint32 app_id = 3;
   */
  appId: number;

  /**
   * @generated from field: optional string filename = 4;
   */
  filename: string;

  /**
   * @generated from field: optional fixed64 steamid_creator = 5;
   */
  steamidCreator: bigint;

  /**
   * @generated from field: optional uint32 file_size = 6;
   */
  fileSize: number;

  /**
   * @generated from field: optional uint32 compressed_file_size = 7;
   */
  compressedFileSize: number;

  /**
   * @generated from field: optional string rangecheck_host = 8;
   */
  rangecheckHost: string;

  /**
   * @generated from field: optional string file_encoded_sha1 = 9;
   */
  fileEncodedSha1: string;
};

/**
 * Describes the message CMsgClientUFSGetUGCDetailsResponse.
 * Use `create(CMsgClientUFSGetUGCDetailsResponseSchema)` to create a new message.
 */
export const CMsgClientUFSGetUGCDetailsResponseSchema: GenMessage<CMsgClientUFSGetUGCDetailsResponse> = /*@__PURE__*/
  messageDesc(file_steammessages_clientserver_ufs, 1);

/**
 * @generated from message CMsgClientUFSGetSingleFileInfo
 */
export type CMsgClientUFSGetSingleFileInfo = Message<"CMsgClientUFSGetSingleFileInfo"> & {
  /**
   * @generated from field: optional uint32 app_id = 1;
   */
  appId: number;

  /**
   * @generated from field: optional string file_name = 2;
   */
  fileName: string;
};

/**
 * Describes the message CMsgClientUFSGetSingleFileInfo.
 * Use `create(CMsgClientUFSGetSingleFileInfoSchema)` to create a new message.
 */
export const CMsgClientUFSGetSingleFileInfoSchema: GenMessage<CMsgClientUFSGetSingleFileInfo> = /*@__PURE__*/
  messageDesc(file_steammessages_clientserver_ufs, 2);

/**
 * @generated from message CMsgClientUFSGetSingleFileInfoResponse
 */
export type CMsgClientUFSGetSingleFileInfoResponse = Message<"CMsgClientUFSGetSingleFileInfoResponse"> & {
  /**
   * @generated from field: optional int32 eresult = 1 [default = 2];
   */
  eresult: number;

  /**
   * @generated from field: optional uint32 app_id = 2;
   */
  appId: number;

  /**
   * @generated from field: optional string file_name = 3;
   */
  fileName: string;

  /**
   * @generated from field: optional bytes sha_file = 4;
   */
  shaFile: Uint8Array;

  /**
   * @generated from field: optional uint64 time_stamp = 5;
   */
  timeStamp: bigint;

  /**
   * @generated from field: optional uint32 raw_file_size = 6;
   */
  rawFileSize: number;

  /**
   * @generated from field: optional bool is_explicit_delete = 7;
   */
  isExplicitDelete: boolean;
};

/**
 * Describes the message CMsgClientUFSGetSingleFileInfoResponse.
 * Use `create(CMsgClientUFSGetSingleFileInfoResponseSchema)` to create a new message.
 */
export const CMsgClientUFSGetSingleFileInfoResponseSchema: GenMessage<CMsgClientUFSGetSingleFileInfoResponse> = /*@__PURE__*/
  messageDesc(file_steammessages_clientserver_ufs, 3);

/**
 * @generated from message CMsgClientUFSShareFile
 */
export type CMsgClientUFSShareFile = Message<"CMsgClientUFSShareFile"> & {
  /**
   * @generated from field: optional uint32 app_id = 1;
   */
  appId: number;

  /**
   * @generated from field: optional string file_name = 2;
   */
  fileName: string;
};

/**
 * Describes the message CMsgClientUFSShareFile.
 * Use `create(CMsgClientUFSShareFileSchema)` to create a new message.
 */
export const CMsgClientUFSShareFileSchema: GenMessage<CMsgClientUFSShareFile> = /*@__PURE__*/
  messageDesc(file_steammessages_clientserver_ufs, 4);

/**
 * @generated from message CMsgClientUFSShareFileResponse
 */
export type CMsgClientUFSShareFileResponse = Message<"CMsgClientUFSShareFileResponse"> & {
  /**
   * @generated from field: optional int32 eresult = 1 [default = 2];
   */
  eresult: number;

  /**
   * @generated from field: optional fixed64 hcontent = 2 [default = 18446744073709551615];
   */
  hcontent: bigint;
};

/**
 * Describes the message CMsgClientUFSShareFileResponse.
 * Use `create(CMsgClientUFSShareFileResponseSchema)` to create a new message.
 */
export const CMsgClientUFSShareFileResponseSchema: GenMessage<CMsgClientUFSShareFileResponse> = /*@__PURE__*/
  messageDesc(file_steammessages_clientserver_ufs, 5);

