// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file steammessages_clientlanp2p.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_steammessages_base } from "./steammessages_base_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file steammessages_clientlanp2p.proto.
 */
export const file_steammessages_clientlanp2p: GenFile = /*@__PURE__*/
  fileDesc("CiBzdGVhbW1lc3NhZ2VzX2NsaWVudGxhbnAycC5wcm90byKHAQodQ01zZ0NsaWVudExBTlAyUFJlcXVlc3RDaHVua3MSOwoKY2h1bmtfa2V5cxgBIAMoCzInLkNNc2dDbGllbnRMQU5QMlBSZXF1ZXN0Q2h1bmtzLkNodW5rS2V5GikKCENodW5rS2V5EhAKCGRlcG90X2lkGAEgASgNEgsKA3NoYRgCIAEoDCLpAQolQ01zZ0NsaWVudExBTlAyUFJlcXVlc3RDaHVua3NSZXNwb25zZRJJCg9jaHVua19yZXNwb25zZXMYASADKAsyMC5DTXNnQ2xpZW50TEFOUDJQUmVxdWVzdENodW5rc1Jlc3BvbnNlLkNodW5rRGF0YRp1CglDaHVua0RhdGESDgoGcmVzdWx0GAEgASgNEhAKCGRlcG90X2lkGAIgASgNEgsKA3NoYRgDIAEoDBISCgpjaHVua19kYXRhGAQgASgMEhEKCWVuY3J5cHRlZBgFIAEoCBISCgpjb21wcmVzc2VkGAYgASgIImEKGkNNc2dDbGllbnRQZWVyQ2h1bmtSZXF1ZXN0Eg4KBmFwcF9pZBgBIAEoDRIQCghkZXBvdF9pZBgCIAEoDRILCgNzaGEYAyABKAwSFAoMYWNjZXNzX3Rva2VuGAQgASgEIpcBChtDTXNnQ2xpZW50UGVlckNodW5rUmVzcG9uc2USDgoGcmVzdWx0GAEgASgNEg4KBmFwcF9pZBgCIAEoDRIQCghkZXBvdF9pZBgDIAEoDRILCgNzaGEYBCABKAwSEQoJZW5jcnlwdGVkGAUgASgIEhIKCmNvbXByZXNzZWQYBiABKAgSEgoKY2h1bmtfZGF0YRgHIAEoDEIFSAGAAQA", [file_steammessages_base]);

/**
 * @generated from message CMsgClientLANP2PRequestChunks
 */
export type CMsgClientLANP2PRequestChunks = Message<"CMsgClientLANP2PRequestChunks"> & {
  /**
   * @generated from field: repeated CMsgClientLANP2PRequestChunks.ChunkKey chunk_keys = 1;
   */
  chunkKeys: CMsgClientLANP2PRequestChunks_ChunkKey[];
};

/**
 * Describes the message CMsgClientLANP2PRequestChunks.
 * Use `create(CMsgClientLANP2PRequestChunksSchema)` to create a new message.
 */
export const CMsgClientLANP2PRequestChunksSchema: GenMessage<CMsgClientLANP2PRequestChunks> = /*@__PURE__*/
  messageDesc(file_steammessages_clientlanp2p, 0);

/**
 * @generated from message CMsgClientLANP2PRequestChunks.ChunkKey
 */
export type CMsgClientLANP2PRequestChunks_ChunkKey = Message<"CMsgClientLANP2PRequestChunks.ChunkKey"> & {
  /**
   * @generated from field: optional uint32 depot_id = 1;
   */
  depotId: number;

  /**
   * @generated from field: optional bytes sha = 2;
   */
  sha: Uint8Array;
};

/**
 * Describes the message CMsgClientLANP2PRequestChunks.ChunkKey.
 * Use `create(CMsgClientLANP2PRequestChunks_ChunkKeySchema)` to create a new message.
 */
export const CMsgClientLANP2PRequestChunks_ChunkKeySchema: GenMessage<CMsgClientLANP2PRequestChunks_ChunkKey> = /*@__PURE__*/
  messageDesc(file_steammessages_clientlanp2p, 0, 0);

/**
 * @generated from message CMsgClientLANP2PRequestChunksResponse
 */
export type CMsgClientLANP2PRequestChunksResponse = Message<"CMsgClientLANP2PRequestChunksResponse"> & {
  /**
   * @generated from field: repeated CMsgClientLANP2PRequestChunksResponse.ChunkData chunk_responses = 1;
   */
  chunkResponses: CMsgClientLANP2PRequestChunksResponse_ChunkData[];
};

/**
 * Describes the message CMsgClientLANP2PRequestChunksResponse.
 * Use `create(CMsgClientLANP2PRequestChunksResponseSchema)` to create a new message.
 */
export const CMsgClientLANP2PRequestChunksResponseSchema: GenMessage<CMsgClientLANP2PRequestChunksResponse> = /*@__PURE__*/
  messageDesc(file_steammessages_clientlanp2p, 1);

/**
 * @generated from message CMsgClientLANP2PRequestChunksResponse.ChunkData
 */
export type CMsgClientLANP2PRequestChunksResponse_ChunkData = Message<"CMsgClientLANP2PRequestChunksResponse.ChunkData"> & {
  /**
   * @generated from field: optional uint32 result = 1;
   */
  result: number;

  /**
   * @generated from field: optional uint32 depot_id = 2;
   */
  depotId: number;

  /**
   * @generated from field: optional bytes sha = 3;
   */
  sha: Uint8Array;

  /**
   * @generated from field: optional bytes chunk_data = 4;
   */
  chunkData: Uint8Array;

  /**
   * @generated from field: optional bool encrypted = 5;
   */
  encrypted: boolean;

  /**
   * @generated from field: optional bool compressed = 6;
   */
  compressed: boolean;
};

/**
 * Describes the message CMsgClientLANP2PRequestChunksResponse.ChunkData.
 * Use `create(CMsgClientLANP2PRequestChunksResponse_ChunkDataSchema)` to create a new message.
 */
export const CMsgClientLANP2PRequestChunksResponse_ChunkDataSchema: GenMessage<CMsgClientLANP2PRequestChunksResponse_ChunkData> = /*@__PURE__*/
  messageDesc(file_steammessages_clientlanp2p, 1, 0);

/**
 * @generated from message CMsgClientPeerChunkRequest
 */
export type CMsgClientPeerChunkRequest = Message<"CMsgClientPeerChunkRequest"> & {
  /**
   * @generated from field: optional uint32 app_id = 1;
   */
  appId: number;

  /**
   * @generated from field: optional uint32 depot_id = 2;
   */
  depotId: number;

  /**
   * @generated from field: optional bytes sha = 3;
   */
  sha: Uint8Array;

  /**
   * @generated from field: optional uint64 access_token = 4;
   */
  accessToken: bigint;
};

/**
 * Describes the message CMsgClientPeerChunkRequest.
 * Use `create(CMsgClientPeerChunkRequestSchema)` to create a new message.
 */
export const CMsgClientPeerChunkRequestSchema: GenMessage<CMsgClientPeerChunkRequest> = /*@__PURE__*/
  messageDesc(file_steammessages_clientlanp2p, 2);

/**
 * @generated from message CMsgClientPeerChunkResponse
 */
export type CMsgClientPeerChunkResponse = Message<"CMsgClientPeerChunkResponse"> & {
  /**
   * @generated from field: optional uint32 result = 1;
   */
  result: number;

  /**
   * @generated from field: optional uint32 app_id = 2;
   */
  appId: number;

  /**
   * @generated from field: optional uint32 depot_id = 3;
   */
  depotId: number;

  /**
   * @generated from field: optional bytes sha = 4;
   */
  sha: Uint8Array;

  /**
   * @generated from field: optional bool encrypted = 5;
   */
  encrypted: boolean;

  /**
   * @generated from field: optional bool compressed = 6;
   */
  compressed: boolean;

  /**
   * @generated from field: optional bytes chunk_data = 7;
   */
  chunkData: Uint8Array;
};

/**
 * Describes the message CMsgClientPeerChunkResponse.
 * Use `create(CMsgClientPeerChunkResponseSchema)` to create a new message.
 */
export const CMsgClientPeerChunkResponseSchema: GenMessage<CMsgClientPeerChunkResponse> = /*@__PURE__*/
  messageDesc(file_steammessages_clientlanp2p, 3);

