// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file steamnetworkingsockets_messages_certs.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file steamnetworkingsockets_messages_certs.proto.
 */
export const file_steamnetworkingsockets_messages_certs: GenFile = /*@__PURE__*/
  fileDesc("CitzdGVhbW5ldHdvcmtpbmdzb2NrZXRzX21lc3NhZ2VzX2NlcnRzLnByb3RvIoEBCidDTXNnU3RlYW1OZXR3b3JraW5nSWRlbnRpdHlMZWdhY3lCaW5hcnkSEAoIc3RlYW1faWQYECABKAYSFQoNZ2VuZXJpY19ieXRlcxgCIAEoDBIWCg5nZW5lcmljX3N0cmluZxgDIAEoCRIVCg1pcHY2X2FuZF9wb3J0GAQgASgMIooDChxDTXNnU3RlYW1EYXRhZ3JhbUNlcnRpZmljYXRlEkEKCGtleV90eXBlGAEgASgOMiYuQ01zZ1N0ZWFtRGF0YWdyYW1DZXJ0aWZpY2F0ZS5FS2V5VHlwZToHSU5WQUxJRBIQCghrZXlfZGF0YRgCIAEoDBIXCg9sZWdhY3lfc3RlYW1faWQYBCABKAYSSAoWbGVnYWN5X2lkZW50aXR5X2JpbmFyeRgLIAEoCzIoLkNNc2dTdGVhbU5ldHdvcmtpbmdJZGVudGl0eUxlZ2FjeUJpbmFyeRIXCg9pZGVudGl0eV9zdHJpbmcYDCABKAkSIQoZZ2FtZXNlcnZlcl9kYXRhY2VudGVyX2lkcxgFIAMoBxIUCgx0aW1lX2NyZWF0ZWQYCCABKAcSEwoLdGltZV9leHBpcnkYCSABKAcSDwoHYXBwX2lkcxgKIAMoDRIUCgxpcF9hZGRyZXNzZXMYDSADKAkiJAoIRUtleVR5cGUSCwoHSU5WQUxJRBAAEgsKB0VEMjU1MTkQASJ1CiJDTXNnU3RlYW1EYXRhZ3JhbUNlcnRpZmljYXRlU2lnbmVkEgwKBGNlcnQYBCABKAwSEQoJY2Ffa2V5X2lkGAUgASgGEhQKDGNhX3NpZ25hdHVyZRgGIAEoDBIYChBwcml2YXRlX2tleV9kYXRhGAEgASgMIlIKI0NNc2dTdGVhbURhdGFncmFtQ2VydGlmaWNhdGVSZXF1ZXN0EisKBGNlcnQYASABKAsyHS5DTXNnU3RlYW1EYXRhZ3JhbUNlcnRpZmljYXRlQgVIAYABAA");

/**
 * @generated from message CMsgSteamNetworkingIdentityLegacyBinary
 */
export type CMsgSteamNetworkingIdentityLegacyBinary = Message<"CMsgSteamNetworkingIdentityLegacyBinary"> & {
  /**
   * @generated from field: optional fixed64 steam_id = 16;
   */
  steamId: bigint;

  /**
   * @generated from field: optional bytes generic_bytes = 2;
   */
  genericBytes: Uint8Array;

  /**
   * @generated from field: optional string generic_string = 3;
   */
  genericString: string;

  /**
   * @generated from field: optional bytes ipv6_and_port = 4;
   */
  ipv6AndPort: Uint8Array;
};

/**
 * Describes the message CMsgSteamNetworkingIdentityLegacyBinary.
 * Use `create(CMsgSteamNetworkingIdentityLegacyBinarySchema)` to create a new message.
 */
export const CMsgSteamNetworkingIdentityLegacyBinarySchema: GenMessage<CMsgSteamNetworkingIdentityLegacyBinary> = /*@__PURE__*/
  messageDesc(file_steamnetworkingsockets_messages_certs, 0);

/**
 * @generated from message CMsgSteamDatagramCertificate
 */
export type CMsgSteamDatagramCertificate = Message<"CMsgSteamDatagramCertificate"> & {
  /**
   * @generated from field: optional CMsgSteamDatagramCertificate.EKeyType key_type = 1 [default = INVALID];
   */
  keyType: CMsgSteamDatagramCertificate_EKeyType;

  /**
   * @generated from field: optional bytes key_data = 2;
   */
  keyData: Uint8Array;

  /**
   * @generated from field: optional fixed64 legacy_steam_id = 4;
   */
  legacySteamId: bigint;

  /**
   * @generated from field: optional CMsgSteamNetworkingIdentityLegacyBinary legacy_identity_binary = 11;
   */
  legacyIdentityBinary?: CMsgSteamNetworkingIdentityLegacyBinary;

  /**
   * @generated from field: optional string identity_string = 12;
   */
  identityString: string;

  /**
   * @generated from field: repeated fixed32 gameserver_datacenter_ids = 5;
   */
  gameserverDatacenterIds: number[];

  /**
   * @generated from field: optional fixed32 time_created = 8;
   */
  timeCreated: number;

  /**
   * @generated from field: optional fixed32 time_expiry = 9;
   */
  timeExpiry: number;

  /**
   * @generated from field: repeated uint32 app_ids = 10;
   */
  appIds: number[];

  /**
   * @generated from field: repeated string ip_addresses = 13;
   */
  ipAddresses: string[];
};

/**
 * Describes the message CMsgSteamDatagramCertificate.
 * Use `create(CMsgSteamDatagramCertificateSchema)` to create a new message.
 */
export const CMsgSteamDatagramCertificateSchema: GenMessage<CMsgSteamDatagramCertificate> = /*@__PURE__*/
  messageDesc(file_steamnetworkingsockets_messages_certs, 1);

/**
 * @generated from enum CMsgSteamDatagramCertificate.EKeyType
 */
export enum CMsgSteamDatagramCertificate_EKeyType {
  /**
   * @generated from enum value: INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: ED25519 = 1;
   */
  ED25519 = 1,
}

/**
 * Describes the enum CMsgSteamDatagramCertificate.EKeyType.
 */
export const CMsgSteamDatagramCertificate_EKeyTypeSchema: GenEnum<CMsgSteamDatagramCertificate_EKeyType> = /*@__PURE__*/
  enumDesc(file_steamnetworkingsockets_messages_certs, 1, 0);

/**
 * @generated from message CMsgSteamDatagramCertificateSigned
 */
export type CMsgSteamDatagramCertificateSigned = Message<"CMsgSteamDatagramCertificateSigned"> & {
  /**
   * @generated from field: optional bytes cert = 4;
   */
  cert: Uint8Array;

  /**
   * @generated from field: optional fixed64 ca_key_id = 5;
   */
  caKeyId: bigint;

  /**
   * @generated from field: optional bytes ca_signature = 6;
   */
  caSignature: Uint8Array;

  /**
   * @generated from field: optional bytes private_key_data = 1;
   */
  privateKeyData: Uint8Array;
};

/**
 * Describes the message CMsgSteamDatagramCertificateSigned.
 * Use `create(CMsgSteamDatagramCertificateSignedSchema)` to create a new message.
 */
export const CMsgSteamDatagramCertificateSignedSchema: GenMessage<CMsgSteamDatagramCertificateSigned> = /*@__PURE__*/
  messageDesc(file_steamnetworkingsockets_messages_certs, 2);

/**
 * @generated from message CMsgSteamDatagramCertificateRequest
 */
export type CMsgSteamDatagramCertificateRequest = Message<"CMsgSteamDatagramCertificateRequest"> & {
  /**
   * @generated from field: optional CMsgSteamDatagramCertificate cert = 1;
   */
  cert?: CMsgSteamDatagramCertificate;
};

/**
 * Describes the message CMsgSteamDatagramCertificateRequest.
 * Use `create(CMsgSteamDatagramCertificateRequestSchema)` to create a new message.
 */
export const CMsgSteamDatagramCertificateRequestSchema: GenMessage<CMsgSteamDatagramCertificateRequest> = /*@__PURE__*/
  messageDesc(file_steamnetworkingsockets_messages_certs, 3);

