// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file webuimessages_achievements.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_steammessages_base } from "./steammessages_base_pb";
import { file_webuimessages_base } from "./webuimessages_base_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file webuimessages_achievements.proto.
 */
export const file_webuimessages_achievements: GenFile = /*@__PURE__*/
  fileDesc("CiB3ZWJ1aW1lc3NhZ2VzX2FjaGlldmVtZW50cy5wcm90byIvCh1DQWNoaWV2ZW1lbnRzX0dldEluZm9fUmVxdWVzdBIOCgZnYW1laWQYASABKAQi8AEKHkNBY2hpZXZlbWVudHNfR2V0SW5mb19SZXNwb25zZRI6CgxhY2hpZXZlbWVudHMYASADKAsyJC5DQWNoaWV2ZW1lbnRzX0dldEluZm9fUmVzcG9uc2UuSW5mbxqRAQoESW5mbxIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEgwKBGRlc2MYAyABKAkSGgoSaW1hZ2VfdXJsX2FjaGlldmVkGAQgASgJEh4KFmltYWdlX3VybF9ub3RfYWNoaWV2ZWQYBSABKAkSEAoIYWNoaWV2ZWQYBiABKAgSEwoLdW5sb2NrX3RpbWUYByABKA0yYAoMQWNoaWV2ZW1lbnRzEkoKB0dldEluZm8SHi5DQWNoaWV2ZW1lbnRzX0dldEluZm9fUmVxdWVzdBofLkNBY2hpZXZlbWVudHNfR2V0SW5mb19SZXNwb25zZRoEgJciAkIFSAGAAQE", [file_steammessages_base, file_webuimessages_base]);

/**
 * @generated from message CAchievements_GetInfo_Request
 */
export type CAchievements_GetInfo_Request = Message<"CAchievements_GetInfo_Request"> & {
  /**
   * @generated from field: optional uint64 gameid = 1;
   */
  gameid: bigint;
};

/**
 * Describes the message CAchievements_GetInfo_Request.
 * Use `create(CAchievements_GetInfo_RequestSchema)` to create a new message.
 */
export const CAchievements_GetInfo_RequestSchema: GenMessage<CAchievements_GetInfo_Request> = /*@__PURE__*/
  messageDesc(file_webuimessages_achievements, 0);

/**
 * @generated from message CAchievements_GetInfo_Response
 */
export type CAchievements_GetInfo_Response = Message<"CAchievements_GetInfo_Response"> & {
  /**
   * @generated from field: repeated CAchievements_GetInfo_Response.Info achievements = 1;
   */
  achievements: CAchievements_GetInfo_Response_Info[];
};

/**
 * Describes the message CAchievements_GetInfo_Response.
 * Use `create(CAchievements_GetInfo_ResponseSchema)` to create a new message.
 */
export const CAchievements_GetInfo_ResponseSchema: GenMessage<CAchievements_GetInfo_Response> = /*@__PURE__*/
  messageDesc(file_webuimessages_achievements, 1);

/**
 * @generated from message CAchievements_GetInfo_Response.Info
 */
export type CAchievements_GetInfo_Response_Info = Message<"CAchievements_GetInfo_Response.Info"> & {
  /**
   * @generated from field: optional string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string desc = 3;
   */
  desc: string;

  /**
   * @generated from field: optional string image_url_achieved = 4;
   */
  imageUrlAchieved: string;

  /**
   * @generated from field: optional string image_url_not_achieved = 5;
   */
  imageUrlNotAchieved: string;

  /**
   * @generated from field: optional bool achieved = 6;
   */
  achieved: boolean;

  /**
   * @generated from field: optional uint32 unlock_time = 7;
   */
  unlockTime: number;
};

/**
 * Describes the message CAchievements_GetInfo_Response.Info.
 * Use `create(CAchievements_GetInfo_Response_InfoSchema)` to create a new message.
 */
export const CAchievements_GetInfo_Response_InfoSchema: GenMessage<CAchievements_GetInfo_Response_Info> = /*@__PURE__*/
  messageDesc(file_webuimessages_achievements, 1, 0);

/**
 * @generated from service Achievements
 */
export const Achievements: GenService<{
  /**
   * @generated from rpc Achievements.GetInfo
   */
  getInfo: {
    methodKind: "unary";
    input: typeof CAchievements_GetInfo_RequestSchema;
    output: typeof CAchievements_GetInfo_ResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_webuimessages_achievements, 0);

